/* ========================================================================= */
/* ------------------------------------------------------------------------- */
/*!
\file         datetimeinterval.h
\date         January 2017
\author       Nicu Tofan

\brief        Contains the definition for DateDateTimeInterval class.

*//*

 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Please read COPYING and README files in root folder
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
/* ------------------------------------------------------------------------- */
/* ========================================================================= */
#ifndef FILTERWIDGET_GUI_DATETIMEINTERVAL_H
#define FILTERWIDGET_GUI_DATETIMEINTERVAL_H
//
//
//
//
/*  INCLUDES    ------------------------------------------------------------ */

#include <dbview/dbview-config.h>

#include <QWidget>

/*  INCLUDES    ============================================================ */
//
//
//
//
/*  DEFINITIONS    --------------------------------------------------------- */

namespace Ui {
class DateTimeInterval;
}

/*  DEFINITIONS    ========================================================= */
//
//
//
//
/*  CLASS    --------------------------------------------------------------- */
namespace filterwidget {
namespace gui {

//! Shows a widget that allows selecting a time interval.
class DBVIEW_EXPORT DateTimeInterval : public QWidget {
    Q_OBJECT

    //
    //
    //
    //
    /*  DEFINITIONS    ----------------------------------------------------- */

    /*  DEFINITIONS    ===================================================== */
    //
    //
    //
    //
    /*  DATA    ------------------------------------------------------------ */

private:

    Ui::DateTimeInterval *ui; /**< automatically generated by Qt from the .ui file */

    /*  DATA    ============================================================ */
    //
    //
    //
    //
    /*  FUNCTIONS    ------------------------------------------------------- */

public:

    explicit DateTimeInterval (
            QWidget *parent = NULL);

    ~DateTimeInterval();

    QDateTime
    startInterval () const;

    QDateTime
    endInterval () const;

    bool
    inclusive () const;

    void
    setStartInterval (
            const QDateTime & value);

    void
    setEndInterval (
            const QDateTime & value);

    void
    setinclusive (
            bool value);

    /*  FUNCTIONS    ======================================================= */
    //
    //
    //
    //

}; /* class DateTimeInterval */
} // namespace gui
} // namespace filterwidget

/*  CLASS    =============================================================== */
//
//
//
//


#endif // FILTERWIDGET_GUI_DATETIMEINTERVAL_H
/* ------------------------------------------------------------------------- */
/* ========================================================================= */
