/* ========================================================================= */
/* ------------------------------------------------------------------------- */
/*!
\file         floatinterval.h
\float         January 2017
\author       Nicu Tofan

\brief        Contains the definition for FloatInterval class.

*//*

 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Please read COPYING and README files in root folder
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*/
/* ------------------------------------------------------------------------- */
/* ========================================================================= */
#ifndef FILTERWIDGET_GUI_FLOATINTERVAL_H
#define FILTERWIDGET_GUI_FLOATINTERVAL_H
//
//
//
//
/*  INCLUDES    ------------------------------------------------------------ */

#include <dbview/dbview-config.h>

#include <QWidget>

/*  INCLUDES    ============================================================ */
//
//
//
//
/*  DEFINITIONS    --------------------------------------------------------- */

namespace Ui {
class FloatInterval;
}

/*  DEFINITIONS    ========================================================= */
//
//
//
//
/*  CLASS    --------------------------------------------------------------- */
namespace filterwidget {
namespace gui {

//! Shows a widget that allows selecting a float interval.
class DBVIEW_EXPORT FloatInterval : public QWidget {
    Q_OBJECT

    //
    //
    //
    //
    /*  DEFINITIONS    ----------------------------------------------------- */

    /*  DEFINITIONS    ===================================================== */
    //
    //
    //
    //
    /*  DATA    ------------------------------------------------------------ */

private:

    Ui::FloatInterval *ui; /**< automatically generated by Qt from the .ui file */

    /*  DATA    ============================================================ */
    //
    //
    //
    //
    /*  FUNCTIONS    ------------------------------------------------------- */

public:

    explicit FloatInterval (
            QWidget *parent = NULL);

    ~FloatInterval();

    double
    startInterval () const;

    double
    endInterval () const;

    bool
    inclusive () const;

    void
    setStartInterval (
            double value);

    void
    setEndInterval (
            double value);

    void
    setInclusive (
            bool value);

    /*  FUNCTIONS    ======================================================= */
    //
    //
    //
    //

}; /* class FloatInterval */
} // namespace gui
} // namespace filterwidget

/*  CLASS    =============================================================== */
//
//
//
//


#endif // FILTERWIDGET_GUI_FLOATINTERVAL_H
/* ------------------------------------------------------------------------- */
/* ========================================================================= */
